slc/myapp/urls.py
from django.urls import path
from . import views

app_name = "myapp"
urlpatterns = [
    path('', views.index, name='index'),
    path('auth/cadastro', views.cadastro, name='cadastro'),
    path('auth/login', views.login, name='login'),
    path('verlistas', views.verlistas, name='verlistas'),
    path('novaLista', views.novalista, name='novalista'),
    path('novoProduto', views.novoproduto, name='novoproduto'),


    path('editar/<int:id>/', views.editar, name='editar'),
    path('deletelista/<int:id>/', views.deleteLista, name='deleteLista'),
    path('deleteproduto/<int:id>/', views.deleteProduto, name='deleteProduto'),
    
]

    

slc/slc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

slc/myapp/models.py
from django.db import models
from django.forms import ModelForm


# Create your models here.
class Lista(models.Model):
    id = models.IntegerField(primary_key=True)
    name_lista = models.CharField(max_length=100)   
    
    def __str__(self):
        return self.name_lista


class Produtos(models.Model):
    id = models.IntegerField(primary_key=True)
    name_produto = models.CharField(default= None, max_length=100)
    valor_produto = models.FloatField(default= 0)
    categoria = models.ForeignKey(Lista, on_delete=models.CASCADE, default=None)

    
    def __sizeof__(self):
        return self.id
    
    '''def total(self):
        result = 0
        for x in Produtos:
            result += (Produtos.valor_produto[x])
        return result #retorna o resultado no fim, como tinhas retorna em cada iteração o 'x'''
    



class CriacaoListas(ModelForm):
    class Meta:
        model = Lista
        fields = ['name_lista']

class CriacaoProduto(ModelForm):
    class Meta:
        model = Produtos
        fields = ['name_produto', 'valor_produto', 'categoria']

slc/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Lista, Produtos, CriacaoListas, CriacaoProduto

from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login




def naologado():
    return HttpResponse('Você nao esta logado')

def index(request):
    return render(request, 'index.html')



def cadastro(request):
    if request.method == "GET":
        return render (request, 'cadastro.html')
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = User.objects.filter(username=username).first()
        if user:
            return HttpResponse("Nome de usuário já existente!")

        user = User.objects.create_user(username=username, password=senha)
        user.save()

        return HttpResponseRedirect("../../")



def login(request):
    if request.method == "GET":
        return render (request, 'login.html')
    else:
        username = request.POST.get('username')
        senha = request.POST.get('senha')

        user = authenticate(username=username, password=senha)
        if user:
            auth_login(request, user)
            return HttpResponseRedirect("../verlistas")
        else:
            return HttpResponse("Email ou senha inválidos, volte e tente logar novamente.")



def verlistas(request):
    if request.user.is_authenticated:
        total = 0
        for prod in Produtos.objects.all():
            total = total + prod.valor_produto
        return render(request, 'verlistas.html', {
            "listas": Lista.objects.all(), "produtos": Produtos.objects.all, "valor" : total
        })
    naologado()


def novalista(request):
    if request.user.is_authenticated:
        formLista = CriacaoListas(request.POST or None)

        if formLista.is_valid():
            formLista.save()
            

        
        return render(request, 'criacaolista.html', {'formLista': formLista})
    
    naologado()


def novoproduto(request):
    if request.user.is_authenticated:
        formProduto = CriacaoProduto(request.POST or None)
        
        if formProduto.is_valid():
            formProduto.save()

        return render(request, 'criacaoproduto.html', {'formProduto' : formProduto})
    naologado()



def editar(request, id):
    produto = Produtos.objects.get(id=id)
    if request.user.is_authenticated:
        formProduto = CriacaoProduto(request.POST or None, instance=produto)
        
        if formProduto.is_valid():
            formProduto.save()
            return HttpResponseRedirect("../../verlistas")

        return render(request, 'update.html', {"produtos":produto, 'formProduto' : formProduto})

    

def deleteLista(request, id):
    lista = Lista.objects.get(id=id)
    lista.delete()
    return HttpResponseRedirect("../../verlistas")

    

def deleteProduto(request, id):
    produto = Produtos.objects.get(id=id)
    produto.delete()
    return HttpResponseRedirect("../../verlistas")

slc/myapp/templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <style>
        body{
            background-color: #fff;
        }

        h1{
            text-align: center;
            color: #000;
        }
        form{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        form > input{
            padding: 10px;
            margin: 5px;
        }

        #aux{
            width: 100%;
            height: 80vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #bloco{
            color: white;
            font-weight: bolder;
            font-size: 1.3em;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #8870ff;
            width: 50%;
            height: 50%;
            border-radius: 10px;
        }
    </style>
</head>
<body>
    <h1>Cadastro</h1>
    
    <div id="aux">
        <div id="bloco">
            <form action="{%url 'myapp:cadastro' %}" method="POST">
                {% csrf_token %}
                <p>Usuário</p>
                <input type="text" placeholder="Username" name="username">
                <p>Senha</p>
                <input type="password" placeholder="Senha" name="senha">
                <input type="submit" value="cadastrar">
        
            </form>
        </div>
    </div>
</body>
</html>

slc/myapp/templates/criacao.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação</title>
</head>
<body>
    <a href="{% url 'myapp:verlistas' %}">Criar Lista ou Adicionar Produto</a>
    <h2>NOVA LISTA</h2>
    <form method="post" aria-required="false">
        {% csrf_token %}

        {{formLista.as_p}}

        <button type="submit">Salvar</button>
    </form>


    <h2>NOVO PRODUTO</h2>
    <form method="post">
        {% csrf_token %}

        {{formProduto.as_p}}

        <button type="submit">Salvar</button>
    </form>
</body>
</html>

slc/myapp/templates/criacaolista.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação</title>
    <style>
        body{
            padding: 25px;
        }

        #aux{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 86vh;
        }
        .bloco{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        .bloco > #links > a{
            border-radius: 7px;
            box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.61);
            background-color: #4932bb;
            color: rgb(228, 228, 228);
            padding: 10px;
            margin: 30px;
            transition: 0.5s;
        }

        
        .bloco > #links > a:hover{
            background-color: #7d67ee;
            color: rgb(228, 228, 228);
        }

        form{
            display: flex;
            align-items: center;
            justify-content: center;
        }

    
    </style>
</head>
<body>
    <div id="aux">
        <div class="bloco">
            <div id="links">
                <a href="{% url 'myapp:verlistas' %}">Ver listas</a>
                <a href="{% url 'myapp:novoproduto' %}">Adicionar Produto</a>
            </div>
        
            <h2 style="color: #4932bb; font-size: 2em;">NOVA LISTA</h2>
            <form method="post" aria-required="false">
                {% csrf_token %}
        
                {{formLista.as_p}}
                <button style="margin-left: 15px;" type="submit">Salvar</button>
            </form>
        </div>
    </div>


    
</body>
</html>

slc/myapp/templates/criacaoproduto.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação</title>
    <style>
        body{
            padding: 25px;
        }

        #aux{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 86vh;
        }
        .bloco{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        #aux > .bloco > #links > a{
            border-radius: 7px;
            box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.61);
            background-color: #4932bb;
            color: rgb(228, 228, 228);
            padding: 10px;
            margin: 30px;
            transition: 0.5s;
        }

        
        .bloco > #links > a:hover{
            background-color: #7d67ee;
            color: rgb(228, 228, 228);
        }

        form{
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>
<body>
    <div id="aux">
        <div class="bloco">
            <div id="links">
                <a href="{% url 'myapp:verlistas' %}">Ver listas</a>
                <a href="{% url 'myapp:novalista' %}">Criar Lista</a>
            </div>
        
        
            <h2 style="color: #4932bb; font-size: 2em;">NOVO PRODUTO</h2>
            <form method="post" aria-required="false">
                {% csrf_token %}
                {{formProduto.as_p}}
                <button type="submit">Salvar</button>
            </form>
        </div>
    </div>


    
</body>
</html>

slc/myapp/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    <style>
        body{
            background-color: #fff;
        }
        h1{
            text-align: center;
            color: #000;
        }

        #links{
            display: flex;
            justify-content: space-around;
            align-items: center;
            height: 70vh;
        }
        #links > .bloco > .button > a{
            color: #8870ff;
            font-weight: bold;
            text-decoration: none;
            padding: 20px 60px;
            

        }
        #links > .bloco > .button > a:hover{
            color: #3517ca;
        }

        .button{
            display: flex;
            align-items: center;
            justify-content: center;
            width: 10vw;
            height: 5vh;
            background-color: rgb(255, 255, 255);
            padding: 10px;
            border-radius: 10px;
            box-shadow: 1px 2px 10px rgba(0, 0, 0, 0.445);
        }



        .bloco{
            display: flex;
            align-items: center;
            justify-content: space-around;
            flex-direction: column;
            width: 40%;
            height: 50vh;
            background-color: #8870ff;
            padding: 1%;
            border-radius: 10px;
            box-shadow: 2px 4px 10px rgba(0, 0, 0, 0.699);
            text-align: center;
        }

        .bloco > h2{
            color: white
        }

    </style>
</head>
<body>
    <h1>CADASTRO/LOGIN</h1>
    <div id="links">
        
        <div class="bloco">
            <h2>Não Possuí Conta? <br> Faça o Cadastro Já!</h2>
            <div class="button"><a href="{% url 'myapp:cadastro' %}">Cadastro</a></div>
        </div>


        <div class="bloco">
            <h2>Já Possui Conta? <br> Então Logue</h2>
            <div class="button"><a href="{% url 'myapp:login' %}">Login</a></div>

        </div>
    </div>


    <p style="color:lightgray">@by maryane</p>
</body>
</html>

slc/myapp/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body{
            background-color: #fff;
        }

        h1{
            text-align: center;
            color: #000;
        }
        form{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        form > input{
            padding: 10px;
            margin: 5px;
        }

        #aux{
            width: 100%;
            height: 80vh;
            display: flex;
            justify-content: center;
            align-items: center;
        }

        #bloco{
            color: white;
            font-weight: bolder;
            font-size: 1.3em;
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #8870ff;
            width: 50%;
            height: 50%;
            border-radius: 10px;
        }

    </style>
</head>
<body>
    <h1>Login</h1>
    
    <div id="aux">
        <div id="bloco">
            <form action="{%url 'myapp:login' %}" method="POST">
                {% csrf_token %}
        
                <input type="text" placeholder="Username" name="username">
                <input type="password" placeholder="Senha" name="senha">
                <input type="submit" value="logar">
        
            </form>
        </div>
    </di>
</body>
</html>

slc/myapp/templates/update.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação</title>
    <style>
        body{
            padding: 25px;
        }

        #aux{
            display: flex;
            justify-content: center;
            align-items: center;
            height: 86vh;
        }
        .bloco{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        #aux > .bloco > #links > a{
            border-radius: 7px;
            box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.61);
            background-color: #4932bb;
            color: rgb(228, 228, 228);
            padding: 10px;
            margin: 30px;
            transition: 0.5s;
        }

        
        .bloco > #links > a:hover{
            background-color: #7d67ee;
            color: rgb(228, 228, 228);
        }

        form{
            display: flex;
            align-items: center;
            justify-content: center;
        }
    </style>
</head>
<body>
    <div id="aux">
        <div class="bloco">
            <div id="links">
                <a href="{% url 'myapp:verlistas' %}">Ver listas</a>
            </div>
        
            <h2>EDITAR PRODUTO</h2>
            <form method="post" aria-required="false">
                {% csrf_token %}
                {{formProduto.as_p}}
                <button type="submit">Update</button>
            </form>
        </div>
    </div>


    
</body>
</html>

slc/myapp/templates/verlistas.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualização</title>
    <style>
        body{
            padding: 25px;
        }

        .bloco{
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }


        .bloco > #links > a{
            border-radius: 7px;
            box-shadow: 1px 1px 10px rgba(0, 0, 0, 0.61);
            background-color: #4932bb;
            color: rgb(228, 228, 228);
            padding: 10px;
            margin: 30px;
            transition: 0.5s;
        }

        .bloco > #links > a:hover{
            background-color: #7d67ee;
            color: rgb(228, 228, 228);
        }

        li{
            list-style: none;
        }
        p{
            margin: 12px;
        }

        p > strong{
            font-size: 1.5em;
            color: #694aff;
        }

        p > a{
            color: #ca2c2c;
        }

        #normal{
            font-size: 1.2em;
            color: #000;
        }

    </style>
</head>
<body>
    <div class="bloco">
        <div id="links">
            <a href="{% url 'myapp:novalista' %}">Criar Lista</a>
            <a href="{% url 'myapp:novoproduto' %}">Adicionar Produto</a>
        </div>


        <h2 style="color: #4932bb; font-size: 2em;">Listas ㅤ|ㅤ Total: R${{valor}}</h2>
        {% for lista in listas %}
            <p><strong>{{ lista.name_lista }}</strong> ㅤㅤ;;ㅤㅤ <a href="{% url 'myapp:deleteLista' lista.id %}">apagarLista</a></p>
            


            {%for produto in produtos%}

                {% if produto.categoria == lista%}
                    <p>
                        Produto:  <strong id="normal">{{produto.name_produto}}</strong> ㅤ  Valor(R$): <strong id="normal">{{produto.valor_produto}}</strong>
                        ㅤㅤ   
                    <a href="{% url 'myapp:editar' produto.id %}">Editar</a> : <a href="{% url 'myapp:deleteProduto' produto.id %}">Apagar</a></p>
                    

                {%endif%}
                
            {% endfor %}
            <p>________________________________________________________________</p>



        {% endfor %}
    </div>


    <p style="color:lightgray">@by maryane</p>
</body>
</html>